server:
  port: 80


eureka:
  client:
    register-with-eureka: true    #表识不向注册中心注册自己
    fetch-registry: true   #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

ribbon:
  #默认feign客户端只等待一秒，但是服务端处理需要超过一秒，导致客户端就不想等待了，直接报错
  ReadTimeout:  5000
  ConnectTimeout: 5000
feign:
  hystrix:
    enabled: true #如果处理自身的容错就开启。开启方式与生产端不一样。
spring:
  application:
    name: cloud-provider-hystrix-order
